import Head from "next/head";
import NavBar from "../components/Navbar";
import Wrapper from "../components/Wrapper";

const Home = () => {
  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eos voluptates minima vel soluta, aliquid, numquam facilis consequatur magni dolor cumque adipisci sed consectetur quaerat repudiandae totam voluptatum veniam placeat fugiat?
    </Wrapper>
  );
};

export default Home;
