import Head from "next/head";
import NavBar from "../components/Navbar";
import Wrapper from "../components/Wrapper";
import Form from "../components/Form";

const Home = () => {
  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Form />
    </Wrapper>
  );
};

export default Home;
